"""
generate_scene_files.py

Creates placeholder YAML scene files in adaptation/scenes/ based on chapter
files in manuscript/chapters/. Does not attempt to infer scene content from
the manuscript text — all fields are left as empty placeholders for manual
completion.

Usage:
    python tools/scripts/generate_scene_files.py
    python tools/scripts/generate_scene_files.py manuscript/chapters/chapter_001.md

If no chapter files are specified, all chapter files in manuscript/chapters/
are processed.
"""

import os
import sys
import glob

CHAPTERS_DIR = os.path.join("manuscript", "chapters")
SCENES_DIR = os.path.join("adaptation", "scenes")

SCENE_PLACEHOLDER_TEMPLATE = """\
# Scene placeholder generated by generate_scene_files.py
# Fill in all fields manually based on the source chapter.

scene_id: "{scene_id}"
chapter: "{chapter_id}"
title: ""
location: ""
time_of_day: ""
characters: []
scene_purpose: ""
emotional_turn: ""
plot_turn: ""
summary: ""
key_dialogue: ""
props: []
continuity_notes: ""
adaptation_notes: ""
status: "placeholder"
"""


def chapter_id_from_filename(filename: str) -> str:
    """Derive a chapter ID like CH01 from a filename like chapter_001.md."""
    basename = os.path.splitext(os.path.basename(filename))[0]
    # Extract trailing number, e.g. "chapter_001" -> "001" -> "CH01"
    parts = basename.split("_")
    try:
        number = int(parts[-1])
        return f"CH{number:02d}"
    except (ValueError, IndexError):
        return basename.upper().replace("_", "")


def generate_scene_placeholder(chapter_file: str, scenes_dir: str) -> None:
    """Generate a single placeholder scene file for a chapter."""
    chapter_id = chapter_id_from_filename(chapter_file)
    scene_id = f"{chapter_id}_SC01"
    output_filename = f"{scene_id}.yaml"
    output_path = os.path.join(os.path.abspath(scenes_dir), output_filename)

    if os.path.exists(output_path):
        print(f"  SKIPPED (already exists): {output_filename}")
        return

    content = SCENE_PLACEHOLDER_TEMPLATE.format(
        scene_id=scene_id,
        chapter_id=chapter_id,
    )

    os.makedirs(os.path.abspath(scenes_dir), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  Created: {output_filename}")


def generate_scene_files(chapter_files: list, scenes_dir: str) -> None:
    """Generate placeholder scene YAML files for a list of chapter files."""
    if not chapter_files:
        print("No chapter files found. Run split_chapters.py first.")
        sys.exit(1)

    print(f"Generating placeholder scene files in '{scenes_dir}'...")
    for chapter_file in sorted(chapter_files):
        generate_scene_placeholder(chapter_file, scenes_dir)

    print(f"\nDone. Edit the scene files in '{scenes_dir}' to add scene details.")
    print("You can add additional scenes per chapter by copying and renaming files.")
    print("Example: CH01_SC01.yaml -> CH01_SC02.yaml, then update scene_id field.")


if __name__ == "__main__":
    if len(sys.argv) > 1:
        # Accept explicit chapter file paths as arguments
        chapter_files = sys.argv[1:]
    else:
        # Default: find all chapter files in the chapters directory
        pattern = os.path.join(os.path.abspath(CHAPTERS_DIR), "chapter_*.md")
        chapter_files = glob.glob(pattern)

    generate_scene_files(chapter_files, SCENES_DIR)
